### ISSUE TITLE
bracket foot mirror

### ISSUE THREAD

**Issue by pdpw** [plenproject/PLEN2#2]
There seems to be a bracket_foot_mirror file missing. Also is there a stl file of the foot from the blender files with the bracket built in?

**Comment by plenproject** [comment]
Hi,

"bracket_foot.stl" (& bracket_foot_mirror.stl) are not using now.
Please print following instead :)

- servo_bracket_ankle_1.stl
- servo_bracket_ankle_1_mirror.stl
- servo_bracket_ankle_2.stl
- servo_bracket_ankle_2_mirror.stl
